### Data Pipeline in Action

##### Import Libraries and Utils

In [25]:
import sys
import os

sys.path.append(os.path.abspath(".."))

In [26]:
from utils.pipeline import Pipeline
from matplotlib import pyplot as plt
import pandas as pd
import numpy as np

pipe = Pipeline()

# querying flights table from travel.sqlite data
df = pipe.fetch_sql_query("SELECT * FROM flights LIMIT 100", "sqlite:///../data/travel.sqlite")
df

,flight_id,flight_no,scheduled_departure,scheduled_arrival,departure_airport,arrival_airport,status,aircraft_code,actual_departure,actual_arrival
0,1185,PG0134,2017-09-10 09:50:00+03,2017-09-10 14:55:00+03,DME,BTK,Scheduled,319,\N,\N
1,3979,PG0052,2017-08-25 14:50:00+03,2017-08-25 17:35:00+03,VKO,HMA,Scheduled,CR2,\N,\N
2,4739,PG0561,2017-09-05 12:30:00+03,2017-09-05 14:15:00+03,VKO,AER,Scheduled,763,\N,\N
3,5502,PG0529,2017-09-12 09:50:00+03,2017-09-12 11:20:00+03,SVO,UFA,Scheduled,763,\N,\N
4,6938,PG0461,2017-09-04 12:25:00+03,2017-09-04 13:20:00+03,SVO,ULV,Scheduled,SU9,\N,\N
...,...,...,...,...,...,...,...,...,...,...
95,70,PG0404,2017-08-30 19:05:00+03,2017-08-30 20:00:00+03,DME,LED,Scheduled,321,\N,\N
96,71,PG0405,2017-08-30 09:35:00+03,2017-08-30 10:30:00+03,DME,LED,Scheduled,321,\N,\N
97,72,PG0402,2017-08-09 12:25:00+03,2017-08-09 13:20:00+03,DME,LED,Arrived,321,2017-08-09 12:27:00+03,2017-08-09 13:23:00+03
98,73,PG0403,2017-08-09 11:25:00+03,2017-08-09 12:20:00+03,DME,LED,Arrived,321,2017-08-09 11:30:00+03,2017-08-09 12:27:00+03
99,74,PG0404,2017-08-09 19:05:00+03,2017-08-09 20:00:00+03,DME,LED,Arrived,321,2017-08-09 22:18:00+03,2017-08-09 23:13:00+03

In [ ]:
# creating an inner join from ticket flights and tickets table
query = pipe.fetch_sql_query(
    "SELECT ticket_flights.ticket_no, ticket_flights.flight_id, ticket_flights.fare_conditions, ticket_flights.amount, tickets.book_ref FROM ticket_flights INNER JOIN tickets ON tickets.ticket_no = ticket_flights.ticket_no LIMIT 100", 
    "sqlite:///../data/travel.sqlite")

query

        ticket_no  flight_id fare_conditions  amount book_ref
0   0005432159776      30625        Business   42100   BA7FAF
1   0005435212351      30625        Business   42100   BEAA38
2   0005435212386      30625        Business   42100   EBE41D
3   0005435212381      30625        Business   42100   86D03C
4   0005432211370      30625        Business   42100   EA2AEA
..            ...        ...             ...     ...      ...
95  0005433367245      24836        Business    9800   DF855A
96  0005433367256      24836        Business    9800   FD30FF
97  0005433367225      24836        Business    9800   C419C8
98  0005433367228      24836         Economy    3300   0EF678
99  0005433367236      24836         Economy    3300   3AED0A

[100 rows x 5 columns]