### Data Pipeline in Data Ingestion

In [49]:
# import necessary libs
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import sys
import os

In [50]:
# import pipeline modules
sys.path.append(os.path.abspath(os.path.join('..')))
from pipeline import extract, transform, load

In [51]:
# data ingestion using csv
df = extract.fetch_file("../data/raw/diabetes.csv")
df.head()

2026-04-04 22:17:10,255 | INFO | Reading the file from: ../data/raw/diabetes.csv

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
# data ingestion from a database engine
db = extract.query_db("sqlite:///../data/raw/nvidia_database.db", "SELECT * FROM products")

transform.standardize_dt(db, 'release_date', 'coerce', "%Y-%m-%d")

2026-04-04 22:17:10,280 | INFO | Fetching from a SQL Database.
2026-04-04 22:17:10,284 | INFO | Standardizing column release_date into <built-in function format> format.

    product_id         product_name        category release_date     price
0            1             RTX 4090             GPU   2023-01-15   1599.99
1            2             RTX 4080             GPU   2022-11-16   1199.99
2            3             RTX 4070             GPU   2023-03-08    599.99
3            4          Jetson Nano  AI Accelerator   2022-05-20     99.99
4            5      Jetson AGX Orin  AI Accelerator   2023-06-10   1999.99
5            6          DGX Station          Server   2023-08-01   8999.99
6            7     A100 Tensor Core  AI Accelerator   2021-07-15  14999.99
7            8     H100 Tensor Core  AI Accelerator   2022-10-10  19999.99
8            9     GeForce GTX 1660             GPU   2019-02-22    279.99
9           10              Titan V             GPU   2017-12-07   2999.99
10          11     GeForce RTX 3060             GPU   2021-10-01    349.99
11          12     GeForce GTX 1080             GPU   2016-05-27    499.99
12          13          NVIDIA V100  AI Accelerator   2017-06-10   8000.00
13          14           NVIDIA A40  AI Accelerator   2020-09-15   2500.00
14          15  NVIDIA Quadro GV100             GPU   2018-04-15   8999.00